version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: employee-postgres

    environment:
      POSTGRES_DB: hrdb
      POSTGRES_USER: hradmin
      POSTGRES_PASSWORD: hrpassword

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  employee-app:
    build: .
    container_name: employee-app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

volumes:
  postgres_data: