apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      uid: prometheus
      url: http://monitoring-kube-prometheus-prometheus.monitoring:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: "Alertmanager"
      type: alertmanager
      uid: alertmanager
      url: http://monitoring-kube-prometheus-alertmanager.monitoring:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
    - name: "Loki"
      type: loki
      uid: loki
      url: http://loki:3100
      access: proxy
      isDefault: false
      jsonData: {}
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2026-06-14T22:34:28Z"
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 86.2.3
    chart: kube-prometheus-stack-86.2.3
    grafana_datasource: "1"
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-grafana-datasource
  namespace: monitoring
  resourceVersion: "67513"
  uid: ed7cc058-f008-4617-953f-353045560829
